OPENAI_API_KEY = "sk-xxxx"
OPENAI_MODEL = "deepseek-chat"
OPENAI_BASE_URL = "https://api.deepseek.com"

NEO4J_URI = "bolt://localhost:7687/"
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = "Anti-fraud"
NEO4J_DATABASE = "neo4j"